#!/usr/bin/env python3

import json

import yaml

data = None
with open("bwanga.yml", "r") as f:
    data = yaml.load(f, Loader=yaml.Loader)

with open("dump.json", "w") as f:
    json.dump(data, f, indent=2)
