# This file is generated by generator.py, do not change this file.
# Change conf/config.yml instead.
class CharacterClass(object):
    Unknown = "unknown"
    Champion = "champion"
    Evangelist = "evangelist"
    HellBringer = "hell_bringer"
    Noblesse = "noblesse"
    SilentEye = "silent_eye"
    Trickster = "trickster"
    WreckingBall = "wrecking_ball"
    GrandMaster = "grand_master"
    Desperado = "desperado"
