# This file is generated by generator.py, do not change this file.
# Change desperado config in conf/config.yml instead.
from character.character import Character
from runtime.character.character_class import CharacterClass


class Desperado(Character):
    Attack = "attack"
    Headshot = "headshot"
    WesternFire = "western_fire"
    DeathByRevolver = "death_by_revolver"
    WildShot = "wild_shot"
    MultiHeadshot = "multi_headshot"
    DeathHawk = "death_hawk"
    ScudGenocide = "scud_genocide"
    DeadlyApproach = "deadly_approach"
    Windmill = "windmill"
    StrikeKick = "strike_kick"
    SilverBullet = "silver_bullet"

    def __init__(self, device, ui_ctx):
        super().__init__(device, ui_ctx, CharacterClass.Desperado)
        self.attack = self.register_skill(
            Desperado.Attack,
            {
                "type": "touch",
                "duration": 2,
                "cool_down": 0,
                "delay": 0,
                "exec_limit": {"min_distance": 500},
            },
        )
        self.headshot = self.register_skill(
            Desperado.Headshot,
            {
                "type": "touch",
                "duration": 0.1,
                "cool_down": 0,
                "delay": 0,
                "exec_limit": {"min_distance": 500},
            },
        )
        self.western_fire = self.register_skill(
            Desperado.WesternFire,
            {
                "type": "touch",
                "duration": 0.1,
                "cool_down": 0,
                "delay": 0,
                "exec_limit": {"min_distance": 500},
            },
        )
        self.death_by_revolver = self.register_skill(
            Desperado.DeathByRevolver,
            {
                "type": "swipe_left",
                "coordinate": [1860, 926],
                "duration": 0.1,
                "cool_down": 0,
                "delay": 0,
                "exec_limit": {"min_distance": 0},
            },
        )
        self.wild_shot = self.register_skill(
            Desperado.WildShot,
            {
                "type": "touch",
                "duration": 3,
                "cool_down": 0,
                "delay": 0,
                "exec_limit": {"min_distance": 400},
            },
        )
        self.multi_headshot = self.register_skill(
            Desperado.MultiHeadshot,
            {
                "type": "touch",
                "duration": 1.5,
                "cool_down": 0,
                "delay": 0,
                "exec_limit": {"min_distance": 400},
            },
        )
        self.death_hawk = self.register_skill(
            Desperado.DeathHawk,
            {
                "type": "swipe_right",
                "coordinate": [1860, 926],
                "duration": 1.5,
                "cool_down": 0,
                "delay": 0,
                "exec_limit": {"min_distance": 400},
            },
        )
        self.scud_genocide = self.register_skill(
            Desperado.ScudGenocide,
            {
                "type": "swipe_up",
                "coordinate": [1860, 926],
                "duration": 8,
                "cool_down": 0,
                "delay": 0,
                "exec_limit": {"min_distance": 600},
            },
        )
        self.deadly_approach = self.register_skill(
            Desperado.DeadlyApproach,
            {
                "type": "touch",
                "duration": 1,
                "cool_down": 0,
                "delay": 0,
                "exec_limit": {"min_distance": 500},
            },
        )
        self.windmill = self.register_skill(
            Desperado.Windmill,
            {
                "type": "touch",
                "duration": 1,
                "cool_down": 0,
                "delay": 0,
                "exec_limit": {"min_distance": 250},
            },
        )
        self.strike_kick = self.register_skill(
            Desperado.StrikeKick,
            {
                "type": "touch",
                "duration": 1,
                "cool_down": 0,
                "delay": 0,
                "exec_limit": {"min_distance": 250},
            },
        )
        self.silver_bullet = self.register_skill(
            Desperado.SilverBullet,
            {
                "type": "swipe_down",
                "coordinate": [1860, 926],
                "duration": 0.1,
                "cool_down": 0,
                "delay": 0,
                "exec_limit": {"min_distance": 0},
            },
        )
