# This file is generated by generator.py, do not change this file.
# Change evangelist config in conf/config.yml instead.
from character.character import Character
from runtime.character.character_class import CharacterClass


class Evangelist(Character):
    Attack = "attack"
    ChristeningLight = "christening_light"
    CruxOfVictoria = "crux_of_victoria"
    GrandCrashingCross = "grand_crashing_cross"
    PurifyingLightning = "purifying_lightning"
    SaintWall = "saint_wall"
    ShiningCross = "shining_cross"
    SpearOfVictory = "spear_of_victory"
    ValiantAria = "valiant_aria"

    def __init__(self, device, ui_ctx):
        super().__init__(device, ui_ctx, CharacterClass.Evangelist)
        self.attack = self.register_skill(
            Evangelist.Attack,
            {
                "type": "touch",
                "duration": 1,
                "cool_down": 1,
                "exec_limit": {"min_distance": 500},
            },
        )
        self.christening_light = self.register_skill(
            Evangelist.ChristeningLight,
            {
                "type": "touch",
                "duration": 1,
                "cool_down": 1,
                "exec_limit": {"min_distance": 10},
            },
        )
        self.crux_of_victoria = self.register_skill(
            Evangelist.CruxOfVictoria,
            {
                "type": "swipe_up",
                "coordinate": [1860, 926],
                "duration": 1,
                "cool_down": 1,
                "exec_limit": {"min_distance": 10},
            },
        )
        self.grand_crashing_cross = self.register_skill(
            Evangelist.GrandCrashingCross,
            {
                "type": "touch",
                "duration": 1,
                "cool_down": 1,
                "exec_limit": {"min_distance": 10},
            },
        )
        self.purifying_lightning = self.register_skill(
            Evangelist.PurifyingLightning,
            {
                "type": "swipe_down",
                "coordinate": [1860, 926],
                "duration": 1,
                "cool_down": 1,
                "exec_limit": {"min_distance": 10},
            },
        )
        self.saint_wall = self.register_skill(
            Evangelist.SaintWall,
            {
                "type": "touch",
                "duration": 0.5,
                "cool_down": 1,
                "exec_limit": {"min_distance": 10},
            },
        )
        self.shining_cross = self.register_skill(
            Evangelist.ShiningCross,
            {
                "type": "touch",
                "duration": 1,
                "cool_down": 1,
                "exec_limit": {"min_distance": 10},
            },
        )
        self.spear_of_victory = self.register_skill(
            Evangelist.SpearOfVictory,
            {
                "type": "touch",
                "duration": 0.2,
                "cool_down": 1,
                "exec_limit": {"min_distance": 10},
            },
        )
        self.valiant_aria = self.register_skill(
            Evangelist.ValiantAria,
            {
                "type": "touch",
                "duration": 1,
                "cool_down": 1,
                "exec_limit": {"min_distance": 10},
            },
        )
