# This file is generated by generator.py, do not change this file.
# Change noblesse config in conf/config.yml instead.
from character.character import Character
from runtime.character.character_class import CharacterClass


class Noblesse(Character):
    Attack = "attack"
    ArcaneSwordBlast = "arcane_sword_blast"
    Ascent = "ascent"
    Crescent = "crescent"
    ElementalShift = "elemental_shift"
    Flash = "flash"
    IllusionSword = "illusion_sword"
    SentimentDuFerCritical = "sentiment_du_fer_critical"
    SwiftDemonSlash = "swift_demon_slash"
    SwiftSword = "swift_sword"
    TossingSlash = "tossing_slash"
    UltimateSlayerTechniqueSpacetimeCutter = (
        "ultimate_slayer_technique_spacetime_cutter"
    )

    def __init__(self, device, ui_ctx):
        super().__init__(device, ui_ctx, CharacterClass.Noblesse)
        self.attack = self.register_skill(
            Noblesse.Attack,
            {
                "type": "touch",
                "duration": 1.5,
                "cool_down": 0,
                "exec_limit": {"min_distance": 330},
            },
        )
        self.arcane_sword_blast = self.register_skill(
            Noblesse.ArcaneSwordBlast,
            {
                "type": "swipe_down",
                "coordinate": [1860, 926],
                "duration": 0.2,
                "cool_down": 8,
                "delay": 2,
                "exec_limit": {"min_distance": 600},
            },
        )
        self.ascent = self.register_skill(
            Noblesse.Ascent,
            {
                "type": "touch",
                "duration": 0.2,
                "cool_down": 1,
                "delay": 0.5,
                "exec_limit": {"min_distance": 300},
            },
        )
        self.crescent = self.register_skill(
            Noblesse.Crescent,
            {
                "type": "touch",
                "duration": 0.2,
                "cool_down": 1,
                "exec_limit": {"min_distance": 500},
            },
        )
        self.elemental_shift = self.register_skill(
            Noblesse.ElementalShift,
            {
                "type": "swipe",
                "duration": 0.2,
                "cool_down": 1,
                "delay": 0.5,
                "exec_limit": {"min_distance": 0},
            },
        )
        self.flash = self.register_skill(
            Noblesse.Flash,
            {
                "type": "swipe_right",
                "coordinate": [1860, 926],
                "duration": 0.2,
                "cool_down": 1,
                "delay": 0.5,
                "exec_limit": {"min_distance": 800},
            },
        )
        self.illusion_sword = self.register_skill(
            Noblesse.IllusionSword,
            {
                "type": "touch",
                "duration": 0.2,
                "cool_down": 5,
                "delay": 0.5,
                "exec_limit": {"min_distance": 300},
            },
        )
        self.sentiment_du_fer_critical = self.register_skill(
            Noblesse.SentimentDuFerCritical,
            {
                "type": "swipe_up",
                "coordinate": [1860, 926],
                "duration": 0.2,
                "cool_down": 1,
                "exec_limit": {"min_distance": 0},
            },
        )
        self.swift_demon_slash = self.register_skill(
            Noblesse.SwiftDemonSlash,
            {
                "type": "touch",
                "duration": 0.5,
                "delay": 1,
                "cool_down": 1,
                "exec_limit": {"min_distance": 400},
            },
        )
        self.swift_sword = self.register_skill(
            Noblesse.SwiftSword,
            {
                "type": "touch",
                "duration": 0.2,
                "cool_down": 4,
                "exec_limit": {"min_distance": 300},
            },
        )
        self.tossing_slash = self.register_skill(
            Noblesse.TossingSlash,
            {
                "type": "touch",
                "duration": 0.2,
                "cool_down": 14,
                "exec_limit": {"min_distance": 100},
            },
        )
        self.ultimate_slayer_technique_spacetime_cutter = self.register_skill(
            Noblesse.UltimateSlayerTechniqueSpacetimeCutter,
            {
                "type": "touch",
                "duration": 0.2,
                "cool_down": 1,
                "delay": 5,
                "exec_limit": {"min_distance": 0},
            },
        )
