# This file is generated by generator.py, do not change this file.
# Change silent_eye config in conf/config.yml instead.
from character.character import Character
from runtime.character.character_class import CharacterClass


class SilentEye(Character):
    Attack = "attack"
    AgniPentacle = "agni_pentacle"
    DeadlyEnticer = "deadly_enticer"
    FireWaveSword = "fire_wave_sword"
    ForceWaveNeutral = "force_wave_neutral"
    GhostOrb = "ghost_orb"
    GroundQuaker = "ground_quaker"
    IceWaveSword = "ice_wave_sword"
    MurderousWave = "murderous_wave"
    SpiritCrescent = "spirit_crescent"
    WaveEye = "wave_eye"
    WaveRadiation = "wave_radiation"

    def __init__(self, device, ui_ctx):
        super().__init__(device, ui_ctx, CharacterClass.SilentEye)
        self.attack = self.register_skill(
            SilentEye.Attack,
            {
                "type": "touch",
                "duration": 2,
                "cool_down": 0,
                "delay": 0,
                "exec_limit": {"min_distance": 300},
            },
        )
        self.agni_pentacle = self.register_skill(
            SilentEye.AgniPentacle,
            {
                "type": "swipe_up",
                "coordinate": [1860, 926],
                "duration": 0.5,
                "cool_down": 40,
                "delay": 0,
                "exec_limit": {"min_distance": 300},
            },
        )
        self.deadly_enticer = self.register_skill(
            SilentEye.DeadlyEnticer,
            {
                "type": "swipe_down",
                "coordinate": [1860, 926],
                "duration": 0.5,
                "cool_down": 1,
                "delay": 0,
                "exec_limit": {"min_distance": 400},
            },
        )
        self.fire_wave_sword = self.register_skill(
            SilentEye.FireWaveSword,
            {
                "type": "touch",
                "duration": 0.1,
                "cool_down": 1,
                "delay": 1,
                "exec_limit": {"min_distance": 400},
            },
        )
        self.force_wave_neutral = self.register_skill(
            SilentEye.ForceWaveNeutral,
            {
                "type": "touch",
                "duration": 0.1,
                "cool_down": 5,
                "delay": 0,
                "exec_limit": {"min_distance": 250},
            },
        )
        self.ghost_orb = self.register_skill(
            SilentEye.GhostOrb,
            {
                "type": "touch",
                "duration": 0.8,
                "cool_down": 5,
                "delay": 1,
                "exec_limit": {"min_distance": 300},
            },
        )
        self.ground_quaker = self.register_skill(
            SilentEye.GroundQuaker,
            {
                "type": "swipe_down",
                "coordinate": [1860, 926],
                "duration": 0.5,
                "cool_down": 1,
                "delay": 0,
                "exec_limit": {"min_distance": 400},
            },
        )
        self.ice_wave_sword = self.register_skill(
            SilentEye.IceWaveSword,
            {
                "type": "touch",
                "duration": 0.1,
                "cool_down": 1,
                "delay": 0.3,
                "exec_limit": {"min_distance": 300},
            },
        )
        self.murderous_wave = self.register_skill(
            SilentEye.MurderousWave,
            {
                "type": "swipe_right",
                "coordinate": [1860, 926],
                "duration": 0.1,
                "cool_down": 1,
                "delay": 0.8,
                "exec_limit": {"min_distance": 0},
            },
        )
        self.spirit_crescent = self.register_skill(
            SilentEye.SpiritCrescent,
            {
                "type": "touch",
                "duration": 0.8,
                "cool_down": 1,
                "delay": 0,
                "exec_limit": {"min_distance": 200},
            },
        )
        self.wave_eye = self.register_skill(
            SilentEye.WaveEye,
            {
                "type": "touch",
                "duration": 0.2,
                "cool_down": 1,
                "delay": 0,
                "exec_limit": {"min_distance": 0},
            },
        )
        self.wave_radiation = self.register_skill(
            SilentEye.WaveRadiation,
            {
                "type": "touch",
                "duration": 0.2,
                "cool_down": 7,
                "delay": 0,
                "exec_limit": {"min_distance": 250},
            },
        )
