# This file is generated by generator.py, do not change this file.
# Change trickster config in conf/config.yml instead.
from character.character import Character
from runtime.character.character_class import CharacterClass


class Trickster(Character):
    Attack = "attack"
    AcidRain = "acid_rain"
    CheekyDollShururu = "cheeky_doll_shururu"
    EnhancedMagicMissile = "enhanced_magic_missile"
    FusionCraft = "fusion_craft"
    Gravitas = "gravitas"
    LavaPotionNo9 = "lava_potion_no_9"
    Lollipop = "lollipop"
    Showtime = "showtime"
    SnowMan = "snow_man"

    def __init__(self, device, ui_ctx):
        super().__init__(device, ui_ctx, CharacterClass.Trickster)
        self.attack = self.register_skill(
            Trickster.Attack,
            {
                "type": "touch",
                "duration": 0.8,
                "cool_down": 0,
                "delay": 0,
                "exec_limit": {"min_distance": 150},
            },
        )
        self.acid_rain = self.register_skill(
            Trickster.AcidRain,
            {
                "type": "swipe_up",
                "coordinate": [1860, 926],
                "duration": 0.5,
                "cool_down": 1,
                "delay": 0,
                "exec_limit": {"min_distance": 200},
            },
        )
        self.cheeky_doll_shururu = self.register_skill(
            Trickster.CheekyDollShururu,
            {
                "type": "touch",
                "duration": 0.1,
                "cool_down": 1,
                "delay": 0,
                "exec_limit": {"min_distance": 200},
            },
        )
        self.enhanced_magic_missile = self.register_skill(
            Trickster.EnhancedMagicMissile,
            {
                "type": "touch",
                "duration": 0.1,
                "cool_down": 1,
                "delay": 0,
                "exec_limit": {"min_distance": 200},
            },
        )
        self.fusion_craft = self.register_skill(
            Trickster.FusionCraft,
            {
                "type": "touch",
                "duration": 0.1,
                "cool_down": 1,
                "delay": 3,
                "exec_limit": {"min_distance": 300},
            },
        )
        self.gravitas = self.register_skill(
            Trickster.Gravitas,
            {
                "type": "touch",
                "duration": 0.1,
                "cool_down": 1,
                "delay": 0,
                "exec_limit": {"min_distance": 300},
            },
        )
        self.lava_potion_no_9 = self.register_skill(
            Trickster.LavaPotionNo9,
            {
                "type": "swipe_down",
                "coordinate": [1860, 926],
                "duration": 0.1,
                "cool_down": 1,
                "delay": 0,
                "exec_limit": {"min_distance": 300},
            },
        )
        self.lollipop = self.register_skill(
            Trickster.Lollipop,
            {
                "type": "swipe_right",
                "coordinate": [1860, 926],
                "duration": 0.1,
                "cool_down": 1,
                "delay": 0,
                "exec_limit": {"min_distance": 0},
            },
        )
        self.showtime = self.register_skill(
            Trickster.Showtime,
            {
                "type": "swipe_left",
                "coordinate": [1860, 926],
                "duration": 0.1,
                "cool_down": 1,
                "delay": 0,
                "exec_limit": {"min_distance": 0},
            },
        )
        self.snow_man = self.register_skill(
            Trickster.SnowMan,
            {
                "type": "touch",
                "duration": 0.1,
                "cool_down": 1,
                "delay": 0,
                "exec_limit": {"min_distance": 100},
            },
        )
